services:
  ms-conta-db:
    image: postgres:16
    container_name: ms-conta-db
    networks:
      - pix-simulator-network
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ms-conta-db
    ports:
      - "5432:5432"

  ms-extrato-db:
    image: mongo:7
    container_name: ms-extrato-db
    ports:
      - "27017:27017"
    networks:
      - pix-simulator-network
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: ms-extrato-db

  kafka:
    container_name: kafka
    image: obsidiandynamics/kafka
    restart: "no"
    ports:
      - "2181:2181"
      - "9092:9092"
    networks:
      - pix-simulator-network
    environment:
      KAFKA_LISTENERS: "INTERNAL://:29092,EXTERNAL://:9092"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka:29092,EXTERNAL://kafka:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_ZOOKEEPER_SESSION_TIMEOUT: "6000"
      KAFKA_RESTART_ATTEMPTS: "10"
      KAFKA_RESTART_DELAY: "5"
      ZOOKEEPER_AUTOPURGE_PURGE_INTERVAL: "0"
    volumes:
      - ./data/kafka/data:/var/lib/kafka/data

  redpanda-console:
    container_name: redpanda
    image: docker.redpanda.com/vectorized/console:latest
    restart: on-failure
    entrypoint: /bin/sh
    command: -c "echo \"$$CONSOLE_CONFIG_FILE\" > /tmp/config.yml; /app/console"
    ports:
      - "8081:8080"
    networks:
      - pix-simulator-network
    environment:
      CONFIG_FILEPATH: /tmp/config.yml
      CONSOLE_CONFIG_FILE: |
        kafka:
          brokers: ["kafka:29092"]
    depends_on:
      - "kafka"

  #Aplicações
  ms-conta:
    build: './ms-conta'
    container_name: ms-conta
    depends_on:
      - kafka
      - ms-conta-db
    networks:
      - pix-simulator-network
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres
     - POSTGRES_DB_URL=jdbc:postgresql://ms-conta-db:5432/ms-conta-db
     - KAFKA_BROKER=kafka:9092
    ports:
    - "8090:8080"

  ms-extrato:
    build: './ms-extrato'
    container_name: ms-extrato
    depends_on:
      - kafka
      - ms-extrato-db
    networks:
      - pix-simulator-network
    environment:
      - KAFKA_BROKER=kafka:29092
      - MONGO_DB_URL=mongodb://root:root@ms-extrato-db:27017/ms-extrato-db?authSource=admin
    ports:
    - "8091:8080"
networks:
  pix-simulator-network: