spring:
  application:
    name: ms-conta
  datasource:
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    url: ${POSTGRES_DB_URL:jdbc:postgresql://localhost:5432/ms-conta-db}
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:9092}
server:
  port: 8080